// Massive word banks for generating rentry.org slugs

export const WORDS_2_3 = [
  'ab','ad','ah','am','an','as','at','ax','be','bi','by','do','eh','em','er',
  'ex','go','ha','he','hi','ho','id','if','in','is','it','la','lo','ma','me',
  'mu','my','no','nu','of','oh','ok','on','op','or','os','ow','ox','pa','pi',
  'qi','re','sh','si','so','ta','ti','to','uh','um','un','up','us','ut','we',
  'wo','xi','xu','ya','ye','yo','za','ace','act','add','age','ago','aid','aim',
  'air','all','and','ant','any','ape','app','arc','are','ark','arm','art','ash',
  'ask','ate','awe','axe','bad','bag','ban','bar','bat','bay','bed','bee','bet',
  'bid','big','bin','bit','bog','bon','bow','box','boy','bud','bug','bun','bus',
  'but','buy','cab','cam','can','cap','car','cat','cob','cod','cog','cop','cos',
  'cot','cow','cry','cub','cud','cup','cur','cut','dab','dad','dam','day','den',
  'dew','did','dig','dim','din','dip','doe','dog','don','dot','dry','dub','dud',
  'due','dug','dun','duo','dye','ear','eat','eel','egg','ego','elk','elm','emu',
  'end','era','eve','ewe','eye','fab','fad','fan','far','fat','fax','fed','fee',
  'fen','few','fig','fin','fir','fit','fix','fly','fob','foe','fog','fop','for',
  'fox','fry','fun','fur','gab','gag','gal','gap','gas','gay','gel','gem','get',
  'gig','gin','gnu','god','got','gum','gun','gus','gut','guy','gym','had','hag',
  'ham','has','hat','hay','hen','her','hew','hex','hid','him','hip','his','hit',
  'hob','hog','hop','hot','how','hub','hue','hug','hum','hut','ice','icy','ids',
  'ill','imp','ink','inn','ion','ire','irk','its','ivy','jab','jag','jam','jar',
  'jaw','jay','jet','jig','job','jog','jot','joy','jug','jut','keg','ken','key',
  'kid','kin','kit','lab','lad','lag','lap','law','lax','lay','lea','led','leg',
  'let','lid','lie','lip','lit','log','lot','low','lug','mad','man','map','mar',
  'mat','maw','max','may','men','met','mid','mix','mob','mod','mom','mop','mow',
  'mrs','mud','mug','mum','nab','nag','nap','nay','net','new','nil','nip','nit',
  'nod','nor','not','now','nub','nun','nut','oak','oar','oat','odd','ode','off',
  'oft','ohm','oil','old','one','opt','orb','ore','our','out','ova','owe','owl',
  'own','pad','pal','pan','pap','par','pat','paw','pay','pea','peg','pen','pep',
  'per','pet','pew','pie','pig','pin','pit','ply','pod','pop','pot','pow','pro',
  'pry','pub','pug','pun','pup','pus','put','rag','ram','ran','rap','rat','raw',
  'ray','red','ref','rev','rib','rid','rig','rim','rip','rob','rod','roe','rot',
  'row','rub','rug','rum','run','rut','rye','sac','sad','sag','sap','sat','saw',
  'say','sea','set','sew','she','shy','sin','sip','sir','sis','sit','six','ski',
  'sky','sly','sob','sod','son','sop','sot','sow','soy','spa','spy','sty','sub',
  'sue','sum','sun','sup','tab','tad','tag','tan','tap','tar','tat','tax','tea',
  'ten','the','thy','tic','tie','tin','tip','tit','toe','ton','too','top','tot',
  'tow','toy','try','tub','tug','tun','tut','two','urn','use','van','vat','vet',
  'vex','via','vie','vim','vow','wad','wag','wan','war','was','wax','way','web',
  'wed','wet','who','why','wig','win','wit','woe','wok','won','woo','wow','yak',
  'yam','yap','yaw','yea','yen','yes','yet','yew','yon','you','zap','zed','zen',
  'zig','zip','zit','zoo',
];

export const WORDS_4 = [
  'able','acid','aged','also','area','army','auto','away','baby','back','ball',
  'band','bank','base','bath','bean','bear','beat','been','beer','bell','belt',
  'bend','best','beta','bike','bill','bind','bird','bite','blow','blue','blur',
  'boat','body','bolt','bomb','bond','bone','book','boom','boot','born','boss',
  'both','bowl','buff','bulk','bull','burn','bury','bush','busy','buzz','cafe',
  'cage','cake','call','calm','came','camp','card','care','cart','case','cash',
  'cast','cave','cell','chat','chef','chip','chop','cite','city','clan','clap',
  'clay','clip','clone','clue','coal','coat','code','coil','coin','cold','cole',
  'colt','coma','come','cook','cool','cope','copy','cord','core','corn','cost',
  'cozy','crab','crew','crop','crow','cube','cult','cure','curl','cute','damp',
  'dare','dark','dart','dash','data','date','dawn','dead','deaf','deal','dean',
  'dear','debt','deck','deed','deem','deep','deer','demo','deny','desk','dial',
  'dice','diet','dirt','disc','dish','disk','dock','does','dome','done','doom',
  'door','dose','dove','down','drag','draw','drew','drip','drop','drum','dual',
  'duck','dude','duke','dull','dump','dune','dunk','dusk','dust','duty','dyed',
  'each','earn','ease','east','easy','edge','edit','else','emit','envy','epic',
  'euro','even','ever','evil','exam','exec','exit','expo','eyed','face','fact',
  'fade','fail','fair','fake','fall','fame','fang','fare','farm','fast','fate',
  'fear','feat','feed','feel','feet','fell','felt','fern','fest','feud','file',
  'fill','film','find','fine','fire','firm','fish','fist','five','flag','flat',
  'flaw','fled','flew','flex','flip','flit','flog','flow','foam','foil','fold',
  'folk','fond','font','food','fool','foot','ford','fore','fork','form','fort',
  'foul','four','free','frog','from','fuel','full','fund','funk','fury','fuse',
  'fuss','gain','gale','game','gang','gape','garb','gash','gate','gave','gaze',
  'gear','gene','gift','gild','gilt','girl','gist','give','glad','glen','glib',
  'glow','glue','glut','gnat','gnaw','goat','goes','gold','golf','gone','good',
  'gown','grab','gram','gray','grew','grid','grim','grin','grip','grit','grow',
  'gulf','guru','gust','guys','hack','hail','hair','hale','half','hall','halt',
  'hand','hang','hare','harm','harp','hash','hasp','hate','haul','have','haze',
  'hazy','head','heal','heap','hear','heat','heed','heel','held','hell','helm',
  'help','hemp','herb','herd','here','hero','hide','high','hike','hill','hilt',
  'hind','hint','hire','hold','hole','holy','home','hone','hood','hook','hope',
  'horn','hose','host','hour','howl','huge','hull','hump','hung','hunt','hurl',
  'hurt','hush','hymn','icon','idea','idle','inch','info','iron','isle','item',
  'jack','jade','jail','jazz','jean','jerk','jest','jinx','jobs','john','join',
  'joke','jolt','jump','june','jury','just','keen','keep','kelp','kept','kick',
  'kill','kind','king','kiss','kite','knee','knew','knit','knob','knot','know',
  'lace','lack','lacy','lady','laid','lake','lamb','lame','lamp','land','lane',
  'lark','lash','lass','last','late','lawn','lazy','lead','leaf','leak','lean',
  'leap','lend','lens','lent','less','lest','levy','liar','lick','lied','lieu',
  'life','lift','like','limb','lime','limp','line','link','lint','lion','list',
  'live','load','loaf','loan','lock','lode','loft','logo','lone','long','look',
  'loom','loop','lord','lore','lose','loss','lost','loud','love','luck','lull',
  'lump','lure','lurk','lush','lust','lynx','mace','made','mail','main','make',
  'male','mall','malt','mane','many','mare','mark','mars','mart','mash','mask',
  'mass','mast','mate','maze','mead','meal','mean','meat','meek','meet','meld',
  'melt','memo','mend','menu','mere','mesh','mess','mica','mice','mild','mile',
  'milk','mill','mime','mind','mine','mini','mint','mire','miss','mist','mite',
  'mitt','moan','moat','mock','mode','mold','mole','molt','monk','mood','moon',
  'moor','more','morn','moss','most','moth','move','much','muck','muff','mule',
  'mull','murk','muse','mush','must','mute','myth','nail','name','nape','navy',
  'near','neat','neck','need','nest','nets','news','next','nice','nick','nine',
  'node','noel','none','noon','norm','nose','note','noun','nova','nude','null',
  'numb','oath','obey','odds','odor','offs','oink','okay','omen','omit','once',
  'only','onto','opal','open','opts','oral','orca','ours','oust','oven','over',
  'owed','owns','pace','pack','pact','page','paid','pail','pain','pair','pale',
  'palm','pane','pang','papa','pare','park','part','pass','past','path','pave',
  'pawn','peak','peal','pear','peat','peck','peek','peel','peer','pelt','pend',
  'pens','pent','perk','perm','pest','pick','pier','pike','pile','pill','pine',
  'pink','pint','pipe','pith','pity','plan','play','plea','plod','plot','plow',
  'ploy','plug','plum','plus','pock','poem','poet','poke','pole','poll','polo',
  'pomp','pond','pony','pool','poor','pope','pops','pore','pork','port','pose',
  'posh','post','pour','pray','prep','prey','prim','prod','prof','prop','prow',
  'puck','pull','pulp','pump','punk','pure','push','quad','quiz','race','rack',
  'raft','rage','raid','rail','rain','rake','ramp','rang','rank','rant','rare',
  'rash','rasp','rate','rave','rays','read','real','reap','rear','reef','reel',
  'rein','rely','rent','rest','rich','ride','rift','rind','ring','riot','ripe',
  'rise','risk','rite','road','roam','roar','robe','rock','rode','role','roll',
  'roof','room','root','rope','rose','rosy','rove','rude','ruin','rule','rump',
  'rung','ruse','rush','rust','sack','safe','sage','said','sail','sake','sale',
  'salt','same','sand','sane','sang','sank','sash','save','scan','scar','seal',
  'seam','sear','seas','seat','sect','seed','seek','seem','seen','self','sell',
  'semi','send','sent','sept','sere','shed','shim','shin','ship','shoe','shoo',
  'shop','shot','show','shut','side','sift','sigh','sign','silk','sill','silo',
  'silt','sing','sink','sire','site','size','skit','slab','slag','slam','slap',
  'slay','sled','slew','slid','slim','slip','slit','slob','slot','slow','slug',
  'slum','slur','smog','snap','snob','snow','snub','snug','soak','soap','soar',
  'sock','soda','sofa','soft','soil','sold','sole','solo','some','soon','soot',
  'sore','sort','soul','sour','span','spar','spec','sped','spin','spit','spot',
  'spry','spur','stab','stag','star','stay','stem','step','stew','stir','stop',
  'stub','stud','stun','such','suck','suit','sulk','sumo','sump','sung','sunk',
  'sure','surf','swan','swap','swim','swob','swum','sync','tack','tact','tail',
  'take','talc','tale','talk','tall','tame','tank','tape','taps','tarn','tart',
  'task','taxi','teak','team','tear','teem','tell','temp','tend','tens','tent',
  'term','tern','test','text','that','them','then','they','thin','this','thou',
  'thud','thus','tick','tide','tidy','tied','tier','tile','till','tilt','time',
  'tint','tiny','tire','toad','toil','told','toll','tomb','tome','tone','took',
  'tool','tops','tore','torn','tort','toss','tour','town','trap','tray','tree',
  'trek','trim','trio','trod','trot','true','tube','tuck','tuft','tuna','tune',
  'turf','turn','tusk','tutu','twig','twin','type','ugly','undo','unit','unto',
  'upon','urge','used','user','vain','vale','vane','vary','vase','vast','veal',
  'veer','veil','vein','vent','verb','very','vest','veto','vice','view','vine',
  'visa','void','volt','vote','wade','wage','wail','wait','wake','walk','wall',
  'wand','want','ward','warm','warn','warp','wart','wary','wash','wasp','wave',
  'wavy','waxy','weak','wean','wear','weed','week','weld','well','welt','went',
  'were','west','what','when','whim','whip','wide','wife','wild','will','wilt',
  'wily','wimp','wind','wine','wing','wink','wipe','wire','wise','wish','wisp',
  'with','woke','wolf','womb','wont','wood','woof','wool','word','wore','work',
  'worm','worn','wove','wrap','wren','yard','yarn','yawn','year','yell','yoga',
  'yoke','your','yurt','zeal','zero','zest','zinc','zone','zoom',
];

export const WORDS_5_PLUS = [
  'about','above','abuse','acted','added','admin','adopt','adult','after','again',
  'agent','agree','ahead','alarm','album','alert','alien','align','alive','alley',
  'allow','alone','along','alpha','alter','amino','among','ample','angel','anger',
  'angle','angry','anime','ankle','annex','apart','apple','apply','arena','argue',
  'arise','armor','array','arrow','aside','asset','atlas','attic','audio','audit',
  'avoid','awake','award','aware','awful','bacon','badge','badly','baker','based',
  'basic','basis','batch','beach','beard','beast','began','begin','being','belly',
  'bench','berry','bible','blank','blast','blaze','bleed','blend','bless','blind',
  'blink','bliss','block','blood','bloom','blown','blues','blunt','board','boast',
  'bonus','boost','booth','bound','brace','brain','brand','brass','brave','bread',
  'break','breed','brick','bride','brief','bring','broad','broke','brook','brown',
  'brush','buddy','build','built','bunch','burst','buyer','cabin','cable','camel',
  'candy','cargo','carry','catch','cause','cease','chain','chair','chalk','chaos',
  'charm','chart','chase','cheap','check','cheek','cheer','chess','chest','chief',
  'child','chile','chill','china','chose','chunk','cisco','civic','civil','claim',
  'clash','class','clean','clear','clerk','click','cliff','climb','cling','clock',
  'clone','close','cloth','cloud','coach','coast','color','comet','comic','coral',
  'could','count','court','cover','crack','craft','crane','crash','crazy','cream',
  'creep','crime','crisp','cross','crowd','crown','crude','crush','cubic','curve',
  'cycle','daddy','daily','dairy','dance','debug','decal','decay','decor','decoy',
  'delay','delta','demon','dense','depot','depth','derby','derby','devil','diary',
  'dirty','dodge','donor','doubt','dough','draft','drain','drake','drama','drank',
  'drape','drawn','dread','dream','dress','dried','drift','drill','drink','drive',
  'drone','drove','drugs','drunk','dryer','dummy','dusty','dwarf','eager','eagle',
  'early','earth','eaten','ebony','eight','elder','elect','elite','email','embed',
  'emoji','empty','enemy','enjoy','enter','entry','equal','equip','error','essay',
  'ethic','event','every','exact','exams','excel','exist','expat','extra','fable',
  'facet','faint','fairy','faith','fancy','fatal','fault','feast','femur','fence',
  'ferry','fetch','fever','fewer','fiber','field','fifth','fifty','fight','filed',
  'final','first','fixed','flair','flame','flank','flare','flash','flask','flesh',
  'flick','flies','float','flock','flood','floor','flora','flour','fluid','flush',
  'flute','focal','focus','foggy','force','forge','forgo','forte','forth','forum',
  'found','foyer','frame','frank','fraud','freak','fresh','front','frost','froze',
  'fruit','funny','gamma','genre','ghost','giant','given','gland','glare','glass',
  'gleam','glide','globe','gloom','glory','gloss','glove','going','grace','grade',
  'graft','grain','grand','grant','grape','graph','grasp','grass','grave','gravel',
  'great','greed','green','greet','grief','grind','groan','groom','gross','group',
  'grove','grown','guard','guess','guest','guide','guild','guilt','guise','gusty',
  'habit','happy','harsh','haste','haunt','haven','heart','heavy','hedge','heist',
  'hello','hence','herbs','honor','horse','hotel','house','hover','human','humor',
  'hurry','hyena','hyper','ideal','image','imply','inbox','index','indie','infra',
  'inner','input','intro','ionic','ivory','jewel','joker','judge','juice','jumbo',
  'karma','kiosk','knife','knock','known','label','labor','lance','laser','latch',
  'later','laugh','layer','learn','lease','leave','legal','lemon','level','lever',
  'light','limit','linen','liner','linux','llama','local','lodge','logic','login',
  'loose','lotus','lover','lower','loyal','lunar','lunch','lyric','macro','magic',
  'major','manga','manor','maple','march','marsh','match','mayor','media','merge',
  'merit','metal','meter','might','minor','minus','mixer','model','modem','money',
  'month','moral','morph','motor','mound','mount','mouse','mouth','moved','movie',
  'multi','mural','music','mysql','naive','nerve','never','niche','night','ninja',
  'noble','noise','north','notch','noted','novel','nurse','ocean','offer','often',
  'omega','onion','onset','opera','orbit','order','organ','other','ought','outer',
  'outdo','owned','owner','oxide','ozone','paint','panda','panel','panic','parse',
  'party','pasta','paste','patch','pause','peace','peach','pearl','penny','perch',
  'phase','phone','photo','piano','piece','pilot','pinch','pitch','pixel','pizza',
  'place','plain','plane','plant','plate','plaza','plead','pleat','pledge','plumb',
  'plume','plump','point','polar','pound','power','press','price','pride','prime',
  'print','prior','prize','probe','proof','proud','prove','proxy','psalm','pulse',
  'punch','pupil','puppy','purse','queen','query','quest','queue','quick','quiet',
  'quota','quote','radar','radio','raise','rally','ranch','range','rapid','ratio',
  'reach','react','ready','realm','rebel','refer','reign','relax','relay','renal',
  'renew','reply','reset','resin','retro','rider','ridge','rifle','right','rigid',
  'rival','river','robin','robot','rocky','rogue','roman','rough','round','route',
  'rover','royal','rugby','ruins','rural','rusty','saint','salad','salon','sandy',
  'sauce','sauna','saved','scale','scare','scene','scent','scope','score','scout',
  'scrap','sedan','seize','sense','serve','setup','seven','shade','shaft','shake',
  'shall','shame','shape','share','shark','sharp','shear','sheep','sheer','sheet',
  'shelf','shell','shift','shine','shirt','shock','shoot','shore','short','shout',
  'shown','shrub','sigma','sight','siege','skill','skull','slate','slave','sleep',
  'slice','slide','slope','sloth','small','smart','smell','smile','smoke','snack',
  'snake','snare','solar','solid','solve','sorry','sound','south','space','spare',
  'spark','spawn','speak','speed','spend','spent','spice','spine','spite','split',
  'spoke','spoon','sport','spray','spree','squad','stack','staff','stage','stain',
  'stair','stake','stale','stalk','stall','stamp','stand','stare','stark','start',
  'state','stays','steak','steal','steam','steel','steep','steer','stern','stick',
  'stiff','still','stock','stone','stood','stool','store','storm','story','stout',
  'stove','strip','stuck','study','stuff','stump','stung','stunt','style','sugar',
  'suite','sunny','super','surge','swamp','sweep','sweet','swept','swift','swing',
  'swirl','swore','sworn','sword','syrup','table','tasty','teach','teeth','tempo',
  'thank','theme','there','thick','thief','thing','think','third','thorn','those',
  'three','threw','throw','thumb','tiger','tight','timer','tired','titan','title',
  'toast','today','token','topic','total','touch','tough','towel','tower','toxic',
  'trace','track','trade','trail','train','trait','tramp','trash','treat','trend',
  'trial','tribe','trick','tried','troop','truck','truly','trump','trunk','trust',
  'truth','tumor','tuner','twice','twist','ultra','under','union','unite','unity',
  'until','upper','upset','urban','usage','users','using','usual','utter','valid',
  'value','valve','vault','venus','verse','video','vigor','vinyl','viola','viral',
  'virus','visit','vista','vital','vivid','vocal','vodka','voice','voter','vowel',
  'vulva','wages','waste','watch','water','waves','wheat','wheel','where','which',
  'while','white','whole','whose','wider','witch','woman','women','world','worry',
  'worse','worst','worth','would','wound','wrath','write','wrong','wrote','yield',
  'young','youth','zebra',
  // 6+ letter words
  'access','accord','across','action','active','actual','adjust','admire','advent',
  'advice','affair','afford','agenda','almost','always','amount','anchor','annual',
  'answer','anyone','anyway','appeal','appear','archer','arctic','around','arrest',
  'arrive','artist','aspect','assert','assess','assign','assist','assume','attach',
  'attack','attend','august','author','avatar','backup','banner','barely','barrel',
  'basket','battle','beacon','beauty','become','before','behalf','behave','behind',
  'belong','beside','beyond','binary','bishop','blanch','blazer','bloody','bonsai',
  'border','borrow','bottle','bottom','bounce','branch','breach','breast','breath',
  'breeze','bridge','bright','broken','bronze','broker','browse','brutal','bubble',
  'bucket','budget','buffer','bumble','bundle','burden','bureau','burner','bypass',
  'cactus','camera','campus','cancel','candle','canvas','carbon','career','casino',
  'castle','casual','caught','center','chance','change','chapel','charge','chrome',
  'church','cinema','circle','circus','cities','clever','client','closed','closer',
  'closet','cloudy','cobalt','coffee','colony','column','combat','comedy','commit',
  'common','convex','cookie','copied','copper','corner','cosmic','costly','cotton',
  'couple','course','cousin','covers','create','credit','crisis','cruise','custom',
  'cyborg','dagger','damage','danger','dating','debate','decade','decent','decide',
  'decode','deeply','defeat','defend','define','degree','delete','demand','denial',
  'deploy','derive','desert','design','desire','detail','detect','device','devote',
  'dialog','diesel','differ','digest','dinner','direct','doctor','domain','donate',
  'donkey','double','dragon','dreamy','driven','driver','during','easily','eating',
  'editor','effect','effort','eighth','eleven','emerge','empire','employ','enable',
  'ending','endure','energy','engage','engine','enough','ensure','entire','entity',
  'equals','equate','escape','estate','evenly','evolve','exceed','except','excite',
  'excuse','exempt','exhort','expand','expect','expert','export','extend','extent',
  'fabric','facial','factor','fairly','fallen','family','famine','famous','farmer',
  'father','fathom','favour','feisty','fellow','female','fierce','figure','filter',
  'finder','finger','finish','flashy','flight','flower','flying','folder','follow',
  'footer','forest','forget','formal','format','former','fossil','foster','fourth',
  'freeze','frenzy','friend','frozen','furrow','fusion','future','gadget','galaxy',
  'gaming','garage','garden','garlic','gather','gazebo','gender','gentle','gerbil',
  'gifted','github','global','glossy','golden','google','gothic','govern','gravel',
  'growth','guitar','gutter','hacker','halves','hamlet','handle','happen','harbor',
  'hardly','hazard','header','health','heaven','height','helmet','herald','herbal',
  'hidden','hinder','hobbit','hockey','hollow','honest','hoodie','horror','hostel',
  'humble','hunger','hunter','hybrid','ignore','illume','impact','import','impose',
  'impure','inches','income','indeed','indoor','infect','inform','inject','inline',
  'injury','insane','insert','inside','insist','intact','intend','intern','invent',
  'invest','invite','inward','island','itself','jacket','jaguar','jargon','jersey',
  'jigsaw','jockey','jungle','junior','kernel','kitten','knight','launch','layout',
  'leader','league','legend','lender','length','lesson','letter','liable','lifted',
  'lights','linear','lining','linked','liquid','listen','litter','lively','lizard',
  'locked','logics','lonely','lookup','lovely','lumber','luxury','lyrics','magnet',
  'maiden','mainly','makeup','manage','mangle','manner','manual','marble','margin',
  'marine','market','marker','markup','master','matter','meadow','medium','melody',
  'member','memory','mental','mentor','merely','method','metric','middle','mighty',
  'miller','mining','minute','mirror','misery','mister','mobile','modern','modest',
  'module','moment','monkey','mortal','mostly','mother','motion','moving','murder',
  'museum','muster','mutant','mutual','myself','mystic','namely','narrow','nation',
  'native','nature','nearby','nearly','neatly','nebula','nicely','nimble','ninety',
  'noodle','normal','notice','notion','novels','number','object','obtain','occupy',
  'offend','office','offset','online','opener','oppose','option','oracle','orange',
  'orchid','ordeal','origin','outage','output','oxygen','oyster','packet','paddle',
  'palace','pallet','pampas','parade','parent','parrot','partly','patent','patron',
  'patter','people','pepper','period','permit','person','phrase','pillar','pirate',
  'plague','planet','player','please','pledge','plenty','pliers','plunge','plural',
  'pocket','poetry','poison','police','policy','polish','polite','ponder','poorly',
  'poplar','portal','poster','potato','potent','potion','powder','prayer','prefix',
  'preset','pretty','prince','prison','profit','prompt','proper','proven','public',
  'pueblo','punish','puppet','purely','pursue','puzzle','python','quaint','quarry',
  'rabbit','racial','radial','radius','random','ranger','rarely','raster','rather',
  'rating','ravine','reader','really','reason','reboot','recall','recent','recipe',
  'record','redeem','reduce','reform','refuge','refuse','regard','regime','region',
  'regret','reject','relate','relief','reload','remain','remark','remedy','remote',
  'remove','render','rental','repair','repeat','report','rescue','resign','resist',
  'resort','result','resume','retail','retain','retire','return','reveal','review',
  'revolt','reward','ribbon','ripple','ritual','robust','rocket','roller','roster',
  'rotate','rough','router','rubber','ruling','rumble','runway','rustic','safari',
  'safely','safety','salary','salmon','saloon','sample','satire','savage','scenic',
  'school','script','scroll','search','season','second','secret','sector','secure',
  'seeing','select','seller','seldom','senior','sensor','series','server','settle',
  'severe','shadow','shaman','shield','should','shower','shrink','sierra','signal',
  'silent','silver','simple','simply','single','sister','sketch','skinny','sleeve',
  'slider','slight','smooth','sniper','social','socket','soften','solely','solemn',
  'source','sphere','spiral','spirit','splash','spoken','sponge','spooky','spread',
  'spring','sprint','square','stable','statue','steady','stereo','stitch','stocks',
  'stoked','stolen','strain','strand','strap','stream','street','stress','strict',
  'stride','strike','string','stripe','strive','stroke','strong','struck','struct',
  'studio','submit','subtle','suburb','sudden','suffer','summit','summon','sunset',
  'superb','supply','surely','survey','switch','symbol','syntax','system','tablet',
  'tackle','tailor','talent','tangle','target','tattoo','temple','tenant','tender',
  'terror','thesis','thirst','threat','thrive','throne','ticket','timely','tissue',
  'toggle','tomato','tongue','torque','toward','trader','travel','treaty','tribal',
  'triple','trophy','tunnel','turkey','turtle','twelve','twenty','typing','ubuntu',
  'undone','unfair','unfold','unholy','unique','unlock','unpack','unsafe','unseen',
  'update','upload','upside','uptown','useful','vacuum','valley','vanish','varied',
  'vector','vendor','verbal','verify','vessel','viewer','violet','virgin','virtue',
  'vision','visual','volume','voyage','vulgar','waiter','walker','wallet','walnut',
  'wander','warden','warmth','washer','wealth','weapon','weekly','weight','wildly',
  'window','winner','winter','wisdom','within','wizard','wonder','worker','worthy',
  'writer','yellow','zenith','zombie','absurd',
  // 7+ letter words
  'abandon','ability','absence','academy','account','achieve','acquire','address',
  'advance','adverse','advisor','airport','alchemy','already','amazing','ancient',
  'angular','antenna','anxiety','anybody','anytime','apparel','applied','approve',
  'archive','arrange','artwork','assault','attempt','auction','auditor','awesome',
  'backlash','balance','banking','bargain','barrier','battery','bearing','because',
  'bedroom','believe','beneath','benefit','besides','between','billion','binding',
  'bitcoin','blanket','blazing','blessed','blocker','blooming','boolean','booster',
  'boulder','bracket','brother','browser','buckets','buffalo','bugbear','builder',
  'burning','cabinet','calcium','caliber','calling','capable','capital','captain',
  'capture','cardiac','careful','carrier','catalog','caution','ceiling','central',
  'certain','chamber','channel','chapter','charter','checked','chicken','chronic',
  'circuit','citizen','claimed','classic','cleaner','climate','clipper','cluster',
  'coastal','coating','collect','college','combine','comfort','command','comment',
  'compact','company','compare','compass','compete','compile','complex','compose',
  'compute','concept','concern','conduct','confirm','connect','consent','consist',
  'consult','contact','contain','content','contest','context','control','convert',
  'cooking','correct','council','counter','country','coupled','courier','crafter',
  'creator','cricket','crimson','crusade','crystal','culture','current','customs',
  'cutting','damaged','dealing','decades','decline','decoded','decrypt','default',
  'defense','deficit','defined','deliver','density','deposit','derived','desktop',
  'despite','destroy','details','develop','devoted','diamond','digital','disable',
  'discard','discord','dismiss','display','dispose','dispute','distant','diverse',
  'divided','divisor','donated','doorway','doubled','drawing','dressed','drifted',
  'driving','droplet','dropout','dynamic','earlier','earning','eastern','ecology',
  'eclipse','economy','edition','editing','educate','elected','elegant','element',
  'elevate','embrace','emerged','emitter','emotion','emperor','enabled','encoder',
  'endless','enforce','engaged','english','enhance','enjoyed','enquiry','episode',
  'essence','eternal','ethical','evening','evident','evolved','examine','example',
  'excerpt','excited','exclude','execute','exhaust','exhibit','existed','expense',
  'exploit','explore','express','extinct','extract','extreme','factoid','factory',
  'faculty','failure','fantasy','fashion','fastest','feature','federal','feeling',
  'fiction','fighter','figured','finance','finding','firefly','fitness','fixture',
  'flatten','flowing','focused','forcing','forever','formula','fortune','forward',
  'founder','freedom','freight','fulfill','funding','further','gadgets','gallery',
  'gateway','gazette','general','genetic','genuine','geology','getting','glacier',
  'glasses','glimpse','globals','goddess','gondola','grading','grammar','granite',
  'granted','graphic','gravity','greater','growing','habitat','halcyon','halfway',
  'handful','handler','handout','hanging','happily','harbors','harmful','harmony',
  'harvest','hashmap','haunted','heading','healthy','hearing','helpful','herself',
  'highway','himself','history','holding','holiday','horizon','horrify','hostile',
  'hosting','however','hunched','hundred','hunting','hydrate','illegal','imagine',
  'imaging','immense','implied','imposed','improve','include','indexed','induced',
  'inflate','inhabit','initial','inquiry','insight','inspect','install','instant',
  'instead','insulin','integer','intense','interim','invalid','inverse','invoice',
  'involve','isotope','journal','journey','justice','justify','keeping','keyhole',
  'keyword','kingdom','kitchen','knitted','labeled','landing','largest','largely',
  'lasting','lateral','laughed','laundry','lawsuit','leading','learned','leather',
  'leaving','lecture','lending','leopard','letters','liberal','liberty','library',
  'licence','lighter','limited','linking','listing','literal','loading','locally',
  'locking','logical','longest','looking','loyalty','luggage','machine','madness',
  'magical','mailbox','mammoth','manager','mandate','mansion','married','masking',
  'massive','mastery','matched','matters','maximal','meaning','measure','medical',
  'meeting','members','mention','mercury','merging','message','microbe','migrate',
  'million','minimal','minimum','miracle','missing','mission','mistake','mixture',
  'mockery','modular','monitor','monster','monthly','morning','mounted','musical',
  'mutable','mystery','natural','nearest','neither','nervous','network','neutral',
  'notable','nothing','noticed','nuclear','nursery','nursing','obvious','offense',
  'offered','offline','ongoing','opening','operate','optimal','ordered','organic',
  'orbital','origami','outline','outlook','outside','overall','overlap','overlay',
  'oversee','package','padding','painful','painted','palette','parking','partial',
  'partner','passage','passing','passion','passive','patient','pattern','payload',
  'payment','penalty','pending','pension','percent','perfect','perhaps','persist',
  'persona','physics','picking','picture','pilgrim','pioneer','pivotal','placing',
  'planned','planner','plastic','plateau','players','pleased','plotted','plumber',
  'podcast','pointed','pointer','polling','polygon','popular','portion','possess',
  'postage','posting','pottery','poverty','powered','precise','predict','premium',
  'prepare','present','pressed','presume','prevent','preview','pricing','primary',
  'printer','privacy','private','problem','process','produce','product','profile',
  'program','project','promise','promote','promise','pronoun','propose','protect',
  'protein','protest','provide','provoke','publish','pulling','pumping','pursued',
  'pushing','pyramid','qualify','quantum','quarter','quickly','radical','railway',
  'rainbow','ranging','ranking','rapidly','reached','reading','realign','reality',
  'realize','receipt','receive','recover','recruit','recycle','reduced','reflect',
  'refresh','refused','regards','related','release','remains','remarks','removal',
  'removed','renamed','renewal','replace','replica','replied','request','require',
  'reserve','reshape','resolve','respect','respond','restore','results','retired',
  'retreat','reunion','reveals','revenue','reverse','revival','revolve','rewrite',
  'routine','royalty','running','rushing','sandbox','scaling','scanner','scatter',
  'scenery','science','scratch','section','segment','seismic','selfish','seminar',
  'sending','serious','servant','service','session','setting','shelter','sheriff',
  'shifted','signals','signing','silence','silicon','similar','sincere','skilled',
  'smoking','snippet','society','soldier','somehow','spanish','speaker','special',
  'specify','sponsor','squeeze','stadium','staging','stamina','startup','station',
  'stealth','storage','strange','strings','studied','subject','sublime','success',
  'suicide','summary','sunburn','sunrise','support','supreme','surface','surgeon',
  'surplus','survive','suspect','sustain','swagger','sweater','syllabus','tangent',
  'teacher','telling','tempest','theorem','therapy','thereby','thought','threads',
  'tilting','tobacco','tonight','toolkit','topical','touched','tourism','towards',
  'tracker','trading','traffic','trainer','transit','trigger','trouble','trusted',
  'tuition','tumbler','turkish','turning','tussled','twelfth','twitter','typical',
  'unaware','undergo','unicode','unified','unlocks','unnamed','updated','upgrade',
  'urgency','usually','utility','utilize','utopian','vacancy','vaccine','vanilla',
  'variety','varying','vehicle','venture','verbose','verdict','version','veteran',
  'vibrant','victory','village','vintage','violent','virtual','visible','visitor',
  'voltage','volumes','vulture','waiting','walking','wanting','warfare','warming',
  'warning','warrant','watcher','wayside','wealthy','weather','website','wedding',
  'weekend','welcome','welfare','western','whether','whisper','widgets','wildest',
  'willing','windows','winning','wireless','wishing','without','witness','working',
  'worship','wrapper','writing','written','younger',
  // Common internet / tech / slang terms
  'copypasta','tutorial','download','template','database','software','hardware',
  'protocol','security','terminal','compiler','debugger','endpoint','frontend',
  'backend','fullstack','devtools','markdown','notebook','playlist','streamer',
  'telegram','whatsapp','snapchat','tiktok','youtube','twitch','spotify',
  'netflix','minecraft','fortnite','valorant','overwatch','terraria','roblox',
  'starcraft','fallout','skyrim','cyberpunk','bloodborne','darksouls','pokemon',
  'digimon','naruto','onepiece','dragonball','bleach','deathnote','jujutsu',
  'chainsaw','dandadan','berserk','vinland','mushoku','shield','konosuba',
  'isekai','shonen','seinen','shoujo','mecha','waifu','husbando','senpai',
  'sensei','kawaii','sugoi','tsundere','yandere','chibi','otaku','weeb',
  'normie','boomer','zoomer','doomer','bloomer','coomer','soyjak','wojak',
  'pepe','doge','bonk','based','cringe','ratio','sigma','grindset','gigachad',
  'copium','hopium','seethe','mald','touch','grass','brainrot','skibidi',
  'gyatt','rizz','bussin','nocap','frfr','deadass','lowkey','highkey',
  'blockchain','ethereum','solana','polygon','cardano','avalanche','polkadot',
  'chainlink','uniswap','opensea','metamask','phantom','ledger','trezor',
  'bitcoin','litecoin','dogecoin','shibainu','safemoon','pancake','sushiswap',
  'airdrop','tokenomics','whitepaper','roadmap','presale','launchpad',
  'staking','farming','liquidity','flashloan','rugpull','moonshot',
  'archlinux','manjaro','fedora','debian','gentoo','nixos','freebsd',
  'neovim','emacs','vscode','sublime','intellij','pycharm','webstorm',
  'typescript','javascript','python','golang','rustlang','clojure','haskell',
  'elixir','phoenix','django','flask','fastapi','express','nextjs','nuxtjs',
  'svelte','angular','reactjs','vuejs','tailwind','bootstrap','bulma',
  'prisma','drizzle','sequelize','mongoose','graphql','restapi','grpc',
  'docker','kubernetes','terraform','ansible','jenkins','gitlab','github',
  'vercel','netlify','railway','heroku','supabase','firebase','appwrite',
  'mongodb','postgres','mariadb','sqlite','redis','rabbitmq','kafka',
  'elasticsearch','prometheus','grafana','datadog','sentry','bugsnag',
  'chatgpt','openai','claude','anthropic','gemini','mistral','llama',
  'huggingface','pytorch','tensorflow','jupyter','pandas','numpy','scipy',
  'matplotlib','seaborn','plotly','streamlit','gradio','langchain',
  'pinecone','chromadb','weaviate','qdrant','milvus','faiss',
  'comfyui','automatic','midjourney','stablediffusion','controlnet','lora',
  'dreambooth','inpainting','img2img','txt2img','upscale','checkpoint',
  'embeddings','tokenizer','transformer','attention','diffusion','sampler',
  'aesthetic','vaporwave','synthwave','retrowave','lofi','chillhop',
  'darkwave','shoegaze','dreampop','postpunk','metalcore','deathcore',
  'grindcore','mathrock','progrock','stoner','sludge','ambient',
  'dungeon','synth','modular','eurorack','midicontroller','drumpad',
  'ableton','flstudio','reaper','bitwig','protools','logicpro',
  'blender','unreal','godot','unity','pygame','raylib','opengl',
  'vulkan','directx','webgl','threejs','babylonjs','pixijs','phaser',
  'monogame','libgdx','defold','construct','gamemaker','rpgmaker',
  'tilemaps','spritesheet','pixelart','voxel','lowpoly','isometric',
  'roguelike','metroidvania','soulslike','bulletheaven','towertdefense',
  'deckbuilder','autobattler','battleroyale','survivalcraft',
  'speedrun','glitchless','anypercent','hundredpercent','toolassisted',
  'homelab','selfhosted','pihole','wireguard','openvpn','tailscale',
  'zerotier','cloudflare','nginx','caddy','traefik','haproxy',
  'proxmox','truenas','unraid','synology','portainer','watchtower',
  'jellyfin','plex','emby','sonarr','radarr','lidarr','prowlarr',
  'jackett','overseerr','requestrr','tautulli','bazarr','readarr',
  'paperless','nextcloud','vaultwarden','bookstack','wikijs','outline',
  'matrix','element','signal','session','briar','simplex','deltachat',
  'mastodon','lemmy','kbin','misskey','pleroma','pixelfed','peertube',
  'nitter','teddit','libreddit','bibliogram','invidious','searxng',
  'privacy','security','encryption','decryption','hashing','signing',
  'certificate','keychain','password','passphrase','totp','fido',
  'yubikey','hardware','firmware','bootloader','kernel','systemd',
  'grub','initramfs','dracut','udev','dbus','polkit','selinux',
  'apparmor','firewall','iptables','nftables','wireguard','openvpn',
  'recipes','cooking','baking','grilling','smoking','fermenting',
  'sourdough','kombucha','kefir','tempeh','kimchi','sauerkraut',
  'espresso','pourover','aeropress','chemex','frenchpress','coldbrew',
  'matcha','sencha','oolong','puerh','rooibos','chamomile',
  'fitness','workout','running','cycling','swimming','climbing',
  'bouldering','hiking','camping','backpacking','bushcraft','survival',
  'gardening','composting','permaculture','hydroponics','aquaponics',
  'mushrooms','foraging','herbalism','botany','ecology','biology',
  'astronomy','astrophysics','cosmology','quantum','relativity',
  'topology','algebra','calculus','geometry','statistics','probability',
  'philosophy','epistemology','ontology','ethics','aesthetics','logic',
  'stoicism','existentialism','nihilism','absurdism','pragmatism',
  'meditation','mindfulness','breathwork','journaling','gratitude',
  'productivity','pomodoro','timeblocking','zettelkasten','secondbrain',
  'bulletjournal','notion','obsidian','logseq','roamresearch','anytype',
  'todoist','ticktick','habitica','beeminder','focusmate','toggl',
  'mechanical','keyboards','switches','keycaps','stabilizers','firmware',
  'ergonomic','splitkeyboard','ortholinear','columnar','qmk','zmk',
  'soldering','desoldering','hotswap','plateless','gasketmount',
  'thinkpad','framework','system76','pinebook','steamdeck','analoguepocket',
  'raspberry','arduino','espressif','teensy','adafruit','sparkfun',
];

// Common rentry-specific patterns people use
export const RENTRY_PATTERNS = [
  'info','note','notes','paste','text','list','links','data','todo','temp',
  'test','demo','draft','docs','wiki','help','faq','rules','about','readme',
  'guide','setup','config','changelog','roadmap','plan','status','update',
  'log','raw','edit','new','old','archive','backup','share','public','private',
  'secret','hidden','anon','random','index','start','intro','home','main','page',
  'post','blog','news','feed','api','dev','prod','staging','beta','alpha',
  'v1','v2','v3','ref','src','lib','pkg','mod','cfg','env','tmp','bin',
  'cmd','cli','gui','web','app','bot','ai','ml','db','io','fs','os',
  'nfo','txt','md','doc','csv','json','yaml','toml','xml','html','css','js',
  'ts','py','rs','go','rb','php','sql','sh','zsh','fish','bash','pwsh',
  'vim','nano','code','idea','atom','kate','gedit','micro','helix',
  'uwu','owo','nya','meow','rawr','blep','boop','yeet','yoink','bruh',
  'gg','wp','gl','hf','ez','rip','lol','lmao','rofl','xd','kek','pog',
  'sus','amogus','sussy','baka','smh','tbh','imo','imho','afaik','tldr',
  'eli5','ama','til','ysk','lpt','psa','rant','vent','meta','oc','ooc',
];

// Number suffixes commonly appended
export const NUMBER_SUFFIXES = [
  '1','2','3','4','5','6','7','8','9','0',
  '10','11','12','13','14','15','20','21','22','23','24','25',
  '42','69','99','100','101','123','200','256','314','365','404',
  '420','500','666','777','888','999','1000','1234','1337','2023','2024','2025',
];

// Separator characters
export const SEPARATORS = ['', '-', '_', '.'];

const CHARS = 'abcdefghijklmnopqrstuvwxyz0123456789';
const ALPHA = 'abcdefghijklmnopqrstuvwxyz';

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randomChars(len: number): string {
  let s = '';
  for (let i = 0; i < len; i++) s += CHARS[Math.floor(Math.random() * CHARS.length)];
  return s;
}

function randomAlpha(len: number): string {
  let s = '';
  for (let i = 0; i < len; i++) s += ALPHA[Math.floor(Math.random() * ALPHA.length)];
  return s;
}

// Different slug generation strategies
const strategies: (() => string)[] = [
  // 1. Single short word (2-3 letters)
  () => pick(WORDS_2_3),
  // 2. Single 4-letter word
  () => pick(WORDS_4),
  // 3. Single 5+ letter word
  () => pick(WORDS_5_PLUS),
  // 4. Rentry-specific pattern
  () => pick(RENTRY_PATTERNS),
  // 5. Word + number
  () => pick([...WORDS_2_3, ...WORDS_4, ...WORDS_5_PLUS]) + pick(NUMBER_SUFFIXES),
  // 6. Word + separator + word
  () => pick([...WORDS_2_3, ...WORDS_4]) + pick(SEPARATORS) + pick([...WORDS_2_3, ...WORDS_4]),
  // 7. Pattern + number
  () => pick(RENTRY_PATTERNS) + pick(NUMBER_SUFFIXES),
  // 8. Random 2-4 chars
  () => randomChars(Math.floor(Math.random() * 3) + 2),
  // 9. Random 5-6 chars
  () => randomChars(Math.floor(Math.random() * 2) + 5),
  // 10. Random alpha 3-5
  () => randomAlpha(Math.floor(Math.random() * 3) + 3),
  // 11. Word + random chars
  () => pick(WORDS_4) + randomChars(Math.floor(Math.random() * 3) + 1),
  // 12. Two 5+ letter words
  () => pick(WORDS_5_PLUS) + pick(SEPARATORS) + pick(WORDS_5_PLUS),
  // 13. Abbreviation style (3-5 uppercase-ish)
  () => randomAlpha(Math.floor(Math.random() * 3) + 3),
  // 14. Pattern + word
  () => pick(RENTRY_PATTERNS) + pick(SEPARATORS) + pick(WORDS_4),
  // 15. Word + separator + number
  () => pick(WORDS_5_PLUS) + pick(SEPARATORS) + pick(NUMBER_SUFFIXES),
  // 16. Simple common patterns with numbers
  () => pick(['my','the','a','i','x','q','z','r','s','t','n','m','p','c','d','f','g','h','j','k','l','b','v','w','y']) + pick(WORDS_4),
  // 17. Three short words
  () => pick(WORDS_2_3) + pick(WORDS_2_3) + pick(WORDS_2_3),
  // 18. Mixed casing attempts (lowercase)
  () => pick(WORDS_5_PLUS).slice(0, Math.floor(Math.random() * 3) + 3) + pick(NUMBER_SUFFIXES),
  // 19. Just numbers (some people use these)
  () => String(Math.floor(Math.random() * 99999)),
  // 20. Common username-style patterns
  () => pick(WORDS_4) + pick(['man','boy','girl','guy','dev','pro','fan','god','king','lord','boss','ace','one','zen','fox','cat','dog','bat','owl','bee']),
];

// Weighted strategy selection - favor strategies more likely to find real pages
const WEIGHTS = [
  8,  // short words - very common
  10, // 4-letter words - very common
  12, // 5+ letter words - most common on rentry
  10, // rentry patterns
  8,  // word + number
  6,  // word + word
  6,  // pattern + number
  4,  // random short
  3,  // random medium
  4,  // random alpha
  4,  // word + random
  4,  // two long words
  3,  // abbreviation
  5,  // pattern + word
  5,  // word + number with separator
  4,  // prefix + word
  3,  // three short words
  4,  // truncated + number
  2,  // just numbers
  4,  // username style
];

const totalWeight = WEIGHTS.reduce((a, b) => a + b, 0);

export function generateRandomSlug(): string {
  let r = Math.random() * totalWeight;
  for (let i = 0; i < strategies.length; i++) {
    r -= WEIGHTS[i];
    if (r <= 0) return strategies[i]().toLowerCase();
  }
  return strategies[0]().toLowerCase();
}
